[build]
publish = "web/public"
command = "make build"

[build.environment]
ZOLA_VERSION = "0.12.2"

[[headers]]
for = "/*"

[headers.values]
  Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
