+++
title = "{{ title | dequote }}"
date = {{ created }}
weight = {{ bip }}
in_search_index = true

[taxonomies]
authors = {{ authors }}

[extra]
bip = {{ bip }}
status = "{{ status }}"
github = "{{ github }}"
+++
