name: update-and-publish

on:
  schedule:
  - cron: '*/10 * * * *'

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: install pandoc
      run: |
        apt update -y
        apt install -y pandoc

    - name: install zola
      run: >
        wget -q -O - "https://github.com/getzola/zola/releases/download/v0.13.0/zola-v0.13.0-x86_64-unknown-linux-gnu.tar.gz"
          | tar xzf - -C ./bin &&
          echo "$PWD/bin" >> $GITHUB_PATH

    - name: Update bitcoin/bips submodule
      run: make bips

    - name: Build static site
      run: make build

    - name: Commit and push
      uses: EndBug/add-and-commit@v7.2.0
      with:
        default_author: github_actions
        branch: master
        message: 'cron: update bips submodule and build'
        push: true
