base_url = "https://bips.dev"

compile_sass = true
external_links_target_blank = true

highlight_code = true
highlight_theme = "ayu-light"

build_search_index = true

ignored_content = [ "*-wordlists.md" ]

taxonomies = [
    { name = "authors" },
    { name = "status" }
]

[search]
# seems to be a comfortable value for now to prevent blowing up the js stack
# when window.searchIndex get initialized
truncate_content_length = 35000
