base_url = "https://bips.dev"

compile_sass = true

highlight_code = true
highlight_theme = "ayu-light"

build_search_index = true

ignored_content = [ "*-wordlists.md" ]

taxonomies = [
    { name = "authors", feed = false }
]

[extra]
